### ISSUE TITLE
TV MODE: Progressive bug

### ISSUE THREAD

**Issue by Jay-Jay-OPL** [AKuHAK/uLaunchELF#15]
There seems to be an odd bug when enabling Progressive in TV MODE in uLE Settings.  Testing this version of **uLE: v4.43a 2018-06-18** commit: **d7c7459** -- also updated to latest version of **FMCB v1.961**

It seems to not take affect when launching uLE for the first time from either the PS2 Browser or etc.

It only seems to take affect when you happen to have a multiple page uLE Skin and you have also adjusted those pages with Progressive Mode enabled.

So it seems that the first page, it doesn't turn on Progressive mode on the TV, but until you switch to a different page within uLE.  And then when you return to the first page, it then is in Progressive Mode.

I've scan my two memory cards (NOTE: I launch FMCB via my 2nd SLOT) or my USB HDD to see if I happen to have another CNF file (LAUNCHELF.CNF) anywhere else, but no, nothing that it could be overriding my settings.

I haven't yet tested this bug without a skin, so perhaps that might be the issue?  But I did go through each page and made sure to enable progressive mode for each page and etc.  So something is amiss here.

I'll report back once I test this without a skin.  The skin I am testing is the one found here: http://www.ps2-home.com/forum/viewtopic.php?f=60&t=2211  -- and like I said before, I made sure to go through each different page (it only has 5 CNF pages) and enable Progressive mode per page via uLE -- not NOTEPAD++ or etc.

P.S. I've created a tutorial to teach others about this new feature: http://www.ps2-home.com/forum/viewtopic.php?f=60&t=5785

**UPDATE:**

Bug still occurs without a skin.

**Comment by sp193** [comment]
Fixed in fd80106.

**Comment by Jay-Jay-OPL** [comment]
@SP193, just wanted to let you know that we got a report over at PS2-HOME: http://www.ps2-home.com/forum/viewtopic.php?f=16&t=6827

It seems that this version of uLE that you offered in the following FMCB install (**Update 2018/12/08: v0.985 (FMCB v1.965) released.** ), you've been providing the **LAUNCHELF.CNF** file with progressive mode being turned on inside the **BOOT** folder.

`TV_mode = 4`

Issue is that some folks that may not have their TV systems to support progressive may get that "black or no screen" issue?  Just thought I'd let you know...

**Comment by sp193** [comment]
I don't know what that individual really did, but the default setting is still [AUTO](https://github.com/AKuHAK/uLaunchELF/blob/master/config.c#L674), which translates to [0](https://github.com/AKuHAK/uLaunchELF/blob/master/launchelf.h#L294).

**Comment by Jay-Jay-OPL** [comment]
No, the issue is that in the FMCB install you provide, it comes with a `LAUNCHELF.CNF` file inside the BOOT folder and this file has that TV Mode set to 4.

So I figure that file is what's causing this issue?

**Comment by Jay-Jay-OPL** [comment]
**UPDATE**:

Just a reminder, you forgot to remove the file I mentioned in my prior reply above for: **[190107]FMCB-1966-bin**

Like I said before, the issue is that that file is defaulted for **TV MODE 4** and well, not everyone uses Progressive Scan (i.e. composite cables or those that may use VGA).  Plus I think it has another default setting that it shouldn't have -- can't remember now...

So the best thing to do is remove it, so uLE can create the file with default settings if not found or use the one found inside **SYS-CONF** folder for others that are simply upgrading.

**Comment by sp193** [comment]
I have done it a while ago. Thanks for the remainder.
